### ISSUE TITLE
TWINT still not working in Gambio

### ISSUE THREAD

**Issue by Pixopax** [mollie/gambio#115]
Hello, BVersion 3.0.24 atstes that it support TWINT now. But I could not get it to work.
Activating in the Module works, but the status of TWINT keeps on deactivated.
I activated it in the Mollie backend. 

How do We use it?

**Comment by logeecom** [comment]
Hello @Pixopax,

Thank you for reaching out to us regarding this issue.

Could you please provide us with more details on the issue you are having with the TWINT payment method?

Are you having trouble displaying it on checkout? Or are you not able to complete a payment with the said method?

Note that we tried to reproduce the issue in a local Gambio store, but we were able to show TWINT and complete an order with it.
Even though TWINT was Disabled for us (Mollie status: Disabled), we managed to display it on checkout since this method requires the Shipping country to be set to Switzerland and the shop currency to be CHF.
![Selection_1471](https://github.com/user-attachments/assets/2c0b95db-522c-462c-b066-7a94e791bc69)
We will check internally why Mollie status remains in Disabled state, even though the payment method works on checkout, but in the meantime, please provide us with the additional information listed above and try to reproduce the issue while using Switzerland and CHF on checkout.

If you have any questions, feel free to let us know.

Kind regards.
