### ISSUE TITLE
Unfortunately, the module does not work

### ISSUE THREAD

**Issue by nstraussaltdorf** [mollie/gambio#55]
Hi there,

I am running Gambio version 4.5.1.1 and have installed the latest Gambio module 3.0.12.

In the module center I get the following error message:

![grafik](https://user-images.githubusercontent.com/26894207/147833832-7d1a2dfb-d73e-427f-ae49-1ba94e089f40.png)

What can this be? I have entered the correct email address + password.

**Comment by nstraussaltdorf** [comment]
Can it be that the access does not work because Mollie has activated a captcha on the website?

**Comment by ristokekovic** [comment]
First of all, please clear the Gambio cache after installing the module by following instructions on the [Wiki page](https://github.com/mollie/gambio/wiki/Installation-and-setup#clear-gambio-cache). You are not seeing the correct error message because of this.

The message you are receiving (and is not clearly visible because of the cache) is that the entered API key is not valid. You have mentioned that you tried to enter the email and password here, but you should instead enter either a live or a test API key, depending on the mollie environment you want to use.

![image](https://user-images.githubusercontent.com/6854736/148372461-a9b2cd75-c4cb-430b-b04a-da38b9a9316a.png)

You can find these API keys on your [mollie dashboard page](https://www.mollie.com/dashboard/developers/api-keys). There is also a direct link to that page from the module from tooltips next to each of the API keys.

![image](https://user-images.githubusercontent.com/6854736/148372571-389ad8f8-2150-46a1-a27c-88282522bef0.png)

Please try authenticating with a valid API key and do not hesitate to contact us again if you get this error again.
