### ISSUE TITLE
Questions about payment surcharge rules

### ISSUE THREAD

**Issue by Peter-Oe** [mollie/gambio#62]
I have just updated the Mollie module for my Gambio (4.5.1.2). I tried the payment surcharge rules and I am wondering, if they are not displayed to the customer. It is not displayed next to the payment method and it is not displayed in the summary. Is it displayed in the checkout on the Mollie website? Nevertheless, when using the "Mollie components" feature, it is not visible?

And one more question: It is possible to configure the "maximum payment surcharge". Is it possible to leave it blank or at '0' to not limit the surcharge? For example 2 % without any limit? 

Best regards, Peter

**Comment by logeecom** [comment]
Hi Peter,

The surcharge rules are not shown to the customer. Only the surcharge amount is calculated based on the surcharge rules. The surcharge amount is displayed next to the payment method and in summary. 

It is necessary to go to the Modules > Order total > added modules and install Mollie Payment Surcharge. Also, this module should be enabled, so the surcharge will be calculated and displayed to the customer.

Actually, if you leave the 'maximum surcharge' blank or set it as zero, the plugin will treat it as there is no surcharge applied to the payment method. It is mandatory to put the 'maximum surcharge' greater than 0 in order to charge customer payment surcharge.

**Comment by Peter-Oe** [comment]
Thanks. I will check this. Is there any installation/configuration manual ? I am wondering, where I could have get this information from.

**Comment by logeecom** [comment]
You can find more information about surcharge configuration in the [Wiki pages](https://github.com/mollie/gambio/wiki/Payment-Methods#surcharge). There is also an [installation](https://github.com/mollie/gambio/wiki/Installation-and-setup) and [configuration](https://github.com/mollie/gambio/wiki/Module-Configuration) manual there.
