### ISSUE TITLE
Some links and Icons within Context-Path do not work

### ISSUE THREAD

**Issue by Peter-Oe** [mollie/gambio#7]
When the Gambio Shop is running under a Context-Path (e. g. https://www.shopdomain.com**/shop/**), some links in the backend do not work. For example: Module Center -> Mollie -> Edit -> "Configure" (Next to a payment mehtod). This link will refer to "https://www.shopdomain.com/admin/modules.php?set=payment&module=mollie_creditcard", which is a white page, since the path does not exist. The link should be: "https://www.shopdomain.com**/shop/**admin/modules.php?set=payment&module=mollie_creditcard"

Furthermore, the payment icons are not displayed. When copying the icons to the ROOT directory, it works. I assume it's the same issue, since the module tries to load the images without the "/shop/" Context-Path.

**Comment by logeecom** [comment]
Dear @Peter-Oe,

Thanks for reaching us.

Our team managed to reproduce and fix the reported issue. Please download the latest version for your Gambio version here:

https://github.com/mollie/gambio/releases

Thank you so much for your attention and participation.
Best regards.

**Comment by Peter-Oe** [comment]
Hi and Thanks. I just updated to the recent 1.0.4 version, but unfortunately, the issue is not fixed. The icons are still not displayed. I cleared the Cache in Gambio as well as in my Chrome browser. What can I do?

**Comment by logeecom** [comment]
Hi @Peter-Oe,

Thanks for reaching us again.

Our team couldn’t reproduce this issue after it has been fixed in the previous release. Tested versions 4.3, 4.1, 4.0, and 3.10 within context path. Please check our screenshot below.

![Selection_313](https://user-images.githubusercontent.com/20204230/105175936-da0a7200-5b24-11eb-80de-ecd652c79b16.png)
![Selection_314 (1)](https://user-images.githubusercontent.com/20204230/105175958-e2fb4380-5b24-11eb-9ab8-87e8e9e9c1b1.png)
![Selection_318](https://user-images.githubusercontent.com/20204230/105175988-ee4e6f00-5b24-11eb-924f-a6be19cf2065.png)

Could you please create a support ticket on Mollie Support?

Please keep in mind that we will need admin and FTP access to check why logos don't show up as a module.

Thank you so much for your attention and participation.
Best regards.

**Comment by Peter-Oe** [comment]
Hi, we performed a complete re-installation of the plug-in and it's working now. Thank you!
